// <auto-generated />
using System;
using EmployeeManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007194955_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManager.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("EmployeeManager.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobPositionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobPositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1995, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "emma.johnson@example.com",
                            FirstName = "Emma",
                            HireDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Johnson",
                            PhoneNumber = "0471000001",
                            Salary = 3400m,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1992, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "lucas.martin@example.com",
                            FirstName = "Lucas",
                            HireDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Martin",
                            PhoneNumber = "0471000002",
                            Salary = 3800m,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1998, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "sophie.williams@example.com",
                            FirstName = "Sophie",
                            HireDate = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 2,
                            LastName = "Williams",
                            PhoneNumber = "0471000003",
                            Salary = 2900m,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1990, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "noah.brown@example.com",
                            FirstName = "Noah",
                            HireDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 5,
                            LastName = "Brown",
                            PhoneNumber = "0471000004",
                            Salary = 3600m,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1996, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "olivia.davis@example.com",
                            FirstName = "Olivia",
                            HireDate = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 3,
                            LastName = "Davis",
                            PhoneNumber = "0471000005",
                            Salary = 3100m,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1993, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "liam.wilson@example.com",
                            FirstName = "Liam",
                            HireDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Wilson",
                            PhoneNumber = "0471000006",
                            Salary = 3500m,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1997, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "mia.anderson@example.com",
                            FirstName = "Mia",
                            HireDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 4,
                            LastName = "Anderson",
                            PhoneNumber = "0471000007",
                            Salary = 2800m,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1994, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "ethan.taylor@example.com",
                            FirstName = "Ethan",
                            HireDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 2,
                            LastName = "Taylor",
                            PhoneNumber = "0471000008",
                            Salary = 3200m,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1999, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "charlotte.thomas@example.com",
                            FirstName = "Charlotte",
                            HireDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 3,
                            LastName = "Thomas",
                            PhoneNumber = "0471000009",
                            Salary = 3000m,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1989, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "james.moore@example.com",
                            FirstName = "James",
                            HireDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Moore",
                            PhoneNumber = "0471000010",
                            Salary = 4100m,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1996, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "amelia.jackson@example.com",
                            FirstName = "Amelia",
                            HireDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 4,
                            LastName = "Jackson",
                            PhoneNumber = "0471000011",
                            Salary = 2700m,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1991, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "benjamin.white@example.com",
                            FirstName = "Benjamin",
                            HireDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 5,
                            LastName = "White",
                            PhoneNumber = "0471000012",
                            Salary = 3900m,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1998, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "isabella.harris@example.com",
                            FirstName = "Isabella",
                            HireDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 3,
                            LastName = "Harris",
                            PhoneNumber = "0471000013",
                            Salary = 3200m,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1994, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "henry.clark@example.com",
                            FirstName = "Henry",
                            HireDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 2,
                            LastName = "Clark",
                            PhoneNumber = "0471000014",
                            Salary = 3000m,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1997, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "ava.lewis@example.com",
                            FirstName = "Ava",
                            HireDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Lewis",
                            PhoneNumber = "0471000015",
                            Salary = 3600m,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1992, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "alexander.walker@example.com",
                            FirstName = "Alexander",
                            HireDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 5,
                            LastName = "Walker",
                            PhoneNumber = "0471000016",
                            Salary = 3300m,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2000, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "emily.hall@example.com",
                            FirstName = "Emily",
                            HireDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 4,
                            LastName = "Hall",
                            PhoneNumber = "0471000017",
                            Salary = 2800m,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1995, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "daniel.young@example.com",
                            FirstName = "Daniel",
                            HireDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Young",
                            PhoneNumber = "0471000018",
                            Salary = 3700m,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1999, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "ella.king@example.com",
                            FirstName = "Ella",
                            HireDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 3,
                            LastName = "King",
                            PhoneNumber = "0471000019",
                            Salary = 2950m,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1993, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "matthew.wright@example.com",
                            FirstName = "Matthew",
                            HireDate = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 2,
                            LastName = "Wright",
                            PhoneNumber = "0471000020",
                            Salary = 3150m,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1996, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "grace.scott@example.com",
                            FirstName = "Grace",
                            HireDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 5,
                            LastName = "Scott",
                            PhoneNumber = "0471000021",
                            Salary = 3450m,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1991, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "samuel.green@example.com",
                            FirstName = "Samuel",
                            HireDate = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 1,
                            LastName = "Green",
                            PhoneNumber = "0471000022",
                            Salary = 4000m,
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1998, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "chloe.baker@example.com",
                            FirstName = "Chloe",
                            HireDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 3,
                            LastName = "Baker",
                            PhoneNumber = "0471000023",
                            Salary = 2850m,
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1995, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "jack.adams@example.com",
                            FirstName = "Jack",
                            HireDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 2,
                            LastName = "Adams",
                            PhoneNumber = "0471000024",
                            Salary = 3500m,
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1997, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "lily.nelson@example.com",
                            FirstName = "Lily",
                            HireDate = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPositionId = 4,
                            LastName = "Nelson",
                            PhoneNumber = "0471000025",
                            Salary = 3100m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("EmployeeManager.Domain.Entities.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaximumSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaximumSalary = 4500m,
                            MinimumSalary = 2800m,
                            Title = "Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            MaximumSalary = 4000m,
                            MinimumSalary = 2500m,
                            Title = "Sales Representative"
                        },
                        new
                        {
                            Id = 3,
                            MaximumSalary = 4000m,
                            MinimumSalary = 2500m,
                            Title = "Marketing Specialist"
                        },
                        new
                        {
                            Id = 4,
                            MaximumSalary = 4200m,
                            MinimumSalary = 2600m,
                            Title = "HR Specialist"
                        },
                        new
                        {
                            Id = 5,
                            MaximumSalary = 4500m,
                            MinimumSalary = 2800m,
                            Title = "Financial Analyst"
                        });
                });

            modelBuilder.Entity("EmployeeManager.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeManager.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManager.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany("Employees")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("EmployeeManager.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeManager.Domain.Entities.JobPosition", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
